### ISSUE TITLE
Lisp error: (void-variable &rest)

### ISSUE THREAD

**Issue by wfranzini** [zenspider/package#13]
Hi, 

I'm using package+ 20170802.2039 installed from melpa under emacs-25.1 (debian package) and package-manifest fails with the following error:
```
Debugger entered--Lisp error: (void-variable &rest)
  topological-sort(((package+)))
  package-transitive-closure((package+))
  package-manifest(package+)
  eval((package-manifest (quote package+)) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

I'm not sure if my configuration is wrong or a bug is affecting package+

ciao
walter franzini

**Comment by zenspider** [comment]
How odd... Looking into it... but that error seems to hint that `&rest` is being treated like a variable?? It's nothing new but maybe I specified it wrong (I mostly code in scheme these days, not elisp, and I get tripped up sometimes)

**Comment by zenspider** [comment]
Can you show me how you call into package+? There isn't even a `&rest` on `topological-sort`

oh... maybe it is leaking with some other impl... maybe I should prefix it?

**Comment by zenspider** [comment]
Try updating to the latest and try again... I renamed `topological-sort`... hopefully that'll take care of it, otherwise I need a repro.

**Comment by zenspider** [comment]
anything?

**Comment by wfranzini** [comment]
Sorry, It works.

thanks
walter
