### ISSUE TITLE
Potential for installing old versions of packages?

### ISSUE THREAD

**Issue by mavit** [zenspider/package#2]
AFAICT, when using package-manifest, package-refresh-contents is called only if there is no cache.  If there is an old cache it will be used.  Presumably this means there is the potential to install an old version of a package if the cache is out of date, which doesn't seem like the behaviour that most users would expect.

OTOH, calling package-refresh-contents is slow, so it wouldn't be acceptable to call it from your .emacs.

Perhaps a compromise is to call package-refresh-contents once from package-manifest if it finds that there are packages in need of installation?

**Comment by zenspider** [comment]
Added a comment. Closing. Thanks for the ticket.
