### ISSUE TITLE
Update Manifest automatically

### ISSUE THREAD

**Issue by moonlite** [zenspider/package#3]
It would be nice if the package-manifest in .emacs would be updated automatically when you install or uninstall a package in the package manager.

It would also be nice if I could initialize package-manifest by printing out the currently installed packages to .emacs. 

Thanks for the great work!

**Comment by zenspider** [comment]
I don't think this has a place in package+ at this time. Closing.

**Comment by moonlite** [comment]
Yeah I'm using Cask+Pallet for this today anyways. :)
